// ============================================================
// IPL Fantasy 2026 — reads from data.json (generated by scrape.py)
// ============================================================

const PTS = { run: 1, wicket: 25, catch: 10, stumping: 5, run_out: 5 };

// ── Cap predictions ───────────────────────────────────────────
const CAP_PREDICTIONS = {
  Adi:    { orange: 'Sanju Samson',     purple: 'Jasprit Bumrah' },
  Kahaan: { orange: 'Shivam Dube',      purple: 'Noor Ahmad' },
  Anmol:  { orange: 'Ishan Kishan',     purple: 'Arshdeep Singh' },
  Krish:  { orange: 'Abhishek Sharma',  purple: 'Matheesha Pathirana' },
  Shyam:  { orange: 'Shubman Gill',     purple: 'Prasidh Krishna' },
};

// ── State ─────────────────────────────────────────────────────
let DATA = null; // raw data.json content

// ── Points calc ───────────────────────────────────────────────
function calcPts(s) {
  return (s.runs      || 0) * PTS.run
       + (s.wickets   || 0) * PTS.wicket
       + (s.catches   || 0) * PTS.catch
       + (s.stumpings || 0) * PTS.stumping
       + (s.run_outs  || 0) * PTS.run_out;
}

// ── Fetch data.json ───────────────────────────────────────────
async function loadData() {
  setStatus('Loading stats...');
  showLoading(true);
  try {
    const res = await fetch(`data.json?_=${Date.now()}`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    DATA = await res.json();
    renderAll();
    const updated = DATA.lastUpdated === 'Never — run scrape.py to load data'
      ? 'No data yet — run scrape.py'
      : `Updated ${new Date(DATA.lastUpdated).toLocaleString()} · ${DATA.matchesLoaded} matches`;
    setStatus(updated);
  } catch (e) {
    setStatus(`Error loading data.json: ${e.message}`);
    console.error(e);
  } finally {
    showLoading(false);
  }
}

// ── Team stats ────────────────────────────────────────────────
function buildTeamStats() {
  const out = {};
  for (const [key, team] of Object.entries(DATA.teams)) {
    let totalPts = 0, totalRuns = 0, totalWkts = 0, totalCatch = 0, totalSt = 0, totalRO = 0;
    const players = team.players.map(p => {
      const s = DATA.players[p.full] || { runs: 0, wickets: 0, catches: 0, stumpings: 0, run_outs: 0, matches: [] };
      const pts = calcPts(s);
      totalPts   += pts;
      totalRuns  += s.runs      || 0;
      totalWkts  += s.wickets   || 0;
      totalCatch += s.catches   || 0;
      totalSt    += s.stumpings || 0;
      totalRO    += s.run_outs  || 0;
      return { ...p, s, pts };
    }).sort((a, b) => b.pts - a.pts);

    out[key] = { ...team, players, totalPts, totalRuns, totalWkts, totalCatch, totalSt, totalRO };
  }
  return out;
}

// ── Render ────────────────────────────────────────────────────
function renderAll() {
  const ts = buildTeamStats();
  renderLeaderboard(ts);
  renderCaps();
  renderTeams(ts);
}

function renderCaps() {
  const order      = ['Adi','Kahaan','Anmol','Krish','Shyam'];
  const teamColors = { Adi:'#1565c0', Kahaan:'#c62828', Anmol:'#e65100', Krish:'#6a1b9a', Shyam:'#2e7d32' };
  const teamNames  = Object.fromEntries(Object.entries(DATA.teams).map(([k,v]) => [k, v.displayName]));
  const allPlayers = Object.values(DATA.teams).flatMap(t => t.players);

  function capCard(key, type) {
    const isOrange = type === 'orange';
    const name  = CAP_PREDICTIONS[key][type];
    const s     = DATA.players[name] || { runs: 0, wickets: 0 };
    const nick  = allPlayers.find(p => p.full === name)?.nick || name.split(' ').pop();
    const stat  = isOrange ? `${s.runs} runs` : `${s.wickets} wkts`;
    const color = teamColors[key];
    return `
      <div class="cap-card ${isOrange ? 'cap-orange' : 'cap-purple'}">
        <div class="cap-card-owner" style="color:${color}">${teamNames[key]}</div>
        <div class="cap-card-player">${nick}</div>
        <div class="cap-card-stat">${stat}</div>
      </div>`;
  }

  document.getElementById('caps-grid').innerHTML = `
    <div class="cap-section">
      <div class="cap-section-label">🟠 Orange Cap</div>
      <div class="cap-cards">${order.map(k => capCard(k, 'orange')).join('')}</div>
    </div>
    <div class="cap-section">
      <div class="cap-section-label">🟣 Purple Cap</div>
      <div class="cap-cards">${order.map(k => capCard(k, 'purple')).join('')}</div>
    </div>`;
}

function renderLeaderboard(ts) {
  const sorted = Object.entries(ts).sort((a, b) => b[1].totalPts - a[1].totalPts);
  const maxPts = sorted[0]?.[1].totalPts || 1;

  document.getElementById('leaderboard').innerHTML = sorted.map(([key, team], i) => {
    const rank  = i + 1;
    const medal = rank === 1 ? '🥇' : rank === 2 ? '🥈' : rank === 3 ? '🥉'
                : `<span style="color:var(--muted);font-size:1rem">${rank}</span>`;
    const barW  = maxPts > 0 ? (team.totalPts / maxPts * 100).toFixed(1) : 0;
    return `
      <div class="lb-row rank-${rank <= 3 ? rank : ''}" onclick="scrollToTeam('${key}')" style="cursor:pointer">
        <div class="lb-rank">${medal}</div>
        <div>
          <div class="lb-name">${team.displayName}</div>
          <div class="lb-sub">
            <span>🏏 ${team.totalRuns} runs</span>
            <span>🎳 ${team.totalWkts} wkts</span>
            <span>🙌 ${team.totalCatch} catches</span>
            <span>🧤 ${team.totalSt} st</span>
            <span>🏃 ${team.totalRO} ro</span>
          </div>
        </div>
        <div class="lb-pts">${team.totalPts.toLocaleString()}<small>pts</small></div>
        <div class="lb-bar-wrap">
          <div class="lb-bar" style="width:${barW}%;background:${team.color}"></div>
        </div>
      </div>`;
  }).join('');
}

function renderTeams(ts) {
  const sorted = Object.entries(ts).sort((a, b) => b[1].totalPts - a[1].totalPts);
  document.getElementById('teams-grid').innerHTML = sorted.map(([key, team]) => `
    <div class="team-card" id="team-${key}">
      <div class="team-header" style="background:linear-gradient(135deg,${team.color},${team.color}bb)">
        <h3>${team.displayName}</h3>
        <div style="text-align:right">
          <div class="team-pts-big">${team.totalPts.toLocaleString()}</div>
          <div class="team-pts-label">points</div>
        </div>
      </div>
      ${team.players.map(p => `
        <div class="player-row" onclick="openPlayerModal('${p.full}','${key}')">
          <div>
            <div class="p-name">${p.nick}</div>
            <div class="p-sub">${p.s.runs}r · ${p.s.wickets}w · ${p.s.catches}c · ${p.s.stumpings}st · ${p.s.run_outs||0}ro</div>
          </div>
          <div class="p-pts">${p.pts}</div>
        </div>`).join('')}
    </div>`).join('');
}

// ── Player modal ──────────────────────────────────────────────
function openPlayerModal(fullName, teamKey) {
  const team   = DATA.teams[teamKey];
  const player = team.players.find(p => p.full === fullName);
  if (!player) return;

  const s     = DATA.players[fullName] || { runs: 0, wickets: 0, catches: 0, stumpings: 0, matches: [] };
  const total = calcPts(s);
  const mc    = s.matches?.length || 0;
  const avg   = mc > 0 ? (total / mc).toFixed(1) : '—';

  const runsP  = (s.runs      || 0) * PTS.run;
  const wktsP  = (s.wickets   || 0) * PTS.wicket;
  const catchP = (s.catches   || 0) * PTS.catch;
  const stP    = (s.stumpings || 0) * PTS.stumping;
  const roP    = (s.run_outs  || 0) * PTS.run_out;

  const matchRows = [...(s.matches || [])]
    .sort((a, b) => new Date(b.date) - new Date(a.date))
    .map(m => {
      const pts = calcPts(m);
      return `<tr>
        <td class="td-match">${m.name}</td>
        <td class="td-date">${m.date || '—'}</td>
        <td>${m.runs}</td>
        <td>${m.wickets}</td>
        <td>${m.catches}</td>
        <td>${m.stumpings}</td>
        <td>${m.run_outs||0}</td>
        <td class="td-pts">${pts}</td>
      </tr>`;
    }).join('');

  document.getElementById('player-modal-content').innerHTML = `
    <div class="pm-name">${player.full}</div>
    <div class="pm-team" style="color:${team.color}">${team.displayName}</div>

    <div class="pm-totals">
      <div class="pm-total-box">
        <div class="tb-val">${total}</div>
        <div class="tb-lbl">Total Points</div>
      </div>
      <div class="pm-total-box secondary">
        <div class="tb-val">${avg}</div>
        <div class="tb-lbl">Avg per match · ${mc} matches played</div>
      </div>
    </div>

    <div class="pm-breakdown">
      <div class="pm-bd-card">
        <div class="bd-val">${s.runs}</div>
        <div class="bd-pts">+${runsP} pts</div>
        <div class="bd-lbl">Runs</div>
      </div>
      <div class="pm-bd-card">
        <div class="bd-val">${s.wickets}</div>
        <div class="bd-pts">+${wktsP} pts</div>
        <div class="bd-lbl">Wickets</div>
      </div>
      <div class="pm-bd-card">
        <div class="bd-val">${s.catches}</div>
        <div class="bd-pts">+${catchP} pts</div>
        <div class="bd-lbl">Catches</div>
      </div>
      <div class="pm-bd-card">
        <div class="bd-val">${s.stumpings}</div>
        <div class="bd-pts">+${stP} pts</div>
        <div class="bd-lbl">Stumpings</div>
      </div>
      <div class="pm-bd-card">
        <div class="bd-val">${s.run_outs||0}</div>
        <div class="bd-pts">+${roP} pts</div>
        <div class="bd-lbl">Run Outs</div>
      </div>
    </div>

    <div class="pm-matches-heading">Match-by-match breakdown</div>
    ${matchRows
      ? `<table class="matches-table">
          <thead><tr><th>Match</th><th>Date</th><th>Runs</th><th>Wkts</th><th>Ctch</th><th>St</th><th>RO</th><th>Pts</th></tr></thead>
          <tbody>${matchRows}</tbody>
        </table>`
      : `<div class="no-data">No matches played yet.</div>`}
  `;
  document.getElementById('player-modal').classList.remove('hidden');
}

function closePlayerModal() {
  document.getElementById('player-modal').classList.add('hidden');
}

function handleModalBackdrop(e) {
  if (e.target === document.getElementById('player-modal')) closePlayerModal();
}

// ── UI helpers ────────────────────────────────────────────────
function showLoading(on) {
  document.getElementById('loading-bar').classList.toggle('hidden', !on);
}
function setStatus(text) {
  document.getElementById('status-line').textContent = text;
}

// ── Leaderboard → team scroll ─────────────────────────────────
function scrollToTeam(key) {
  const el = document.getElementById(`team-${key}`);
  if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

// ── Boot ──────────────────────────────────────────────────────
loadData();
